trigger:none
pr:none

pool:
  vmImage: windows-latest

stages:
  stage:terraform_validate
  displayName:terraform validate and init
  jobs:
     job:
     continueOnError: false
       steps:
       - task: TerraformInstaller@0
         inputs:
           terraformVersion: 'latest'
           displayName: Install Terraform
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        commandOptions: '-var-file="dev/main.tfvars"'
        backendType: 'azurerm'
        backendServiceArm: 'Segun_SPN'
        backendAzureRmSubscriptionId: 'Visual Studio Professional Subscription (9e068657-fdd8-4352-a781-6f669c30da5d)'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'rg-segunterraform'
        backendAzureRmResourceGroupLocation: 'Canada Central'
        backendAzureRmStorageAccountName: 'segunstorage999999'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
        allowTelemetryCollection: false
    - task: TerraformCLI@0
          displayName: Terraform validate
          inputs:
            command: 'validate'
            environmentServiceName: 'Segun_SPN'
            allowTelemetryCollection: false

- stage: terraform_plan
  dependsOn: terraform_validate
  condition: succeeded('terraform_validate')
  displayName: Prepare Terraform and Validate Code
  jobs:
  - job:
    steps:  
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'Segun_SPN'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'rg-segunterraform'
        backendAzureRmResourceGroupLocation: 'Canada Central'
        backendAzureRmStorageAccountName: 'segunstorage999999'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'   
    - task: TerraformCLI@0
      displayName: Terraform plan
      inputs:
        command: 'plan'
        environmentServiceName: 'Segun_SPN'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'
  
- stage: terraform_apply
  condition: succeeded('terraform_plan')
  dependsOn: terraform_plan
  displayName: Prepare Terraform and Validate Code
  jobs:
  - job:
    steps:     
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'Segun_SPN'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'rg-segunterraform'
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'segunstorage999999'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'   
    - task: TerraformCLI@0
      displayName: Terraform apply
      inputs:
        command: 'apply'
        environmentServiceName: 'Segun_SPN'
        commandOptions: '-var-file="dev/main.tfvars"'
        allowTelemetryCollection: false